#!/bin/bash

# have job exit if any command returns with non-zero exit status (aka failure)
set -e

# replace env-name on the right hand side of this line with the name of your conda environment
ENVNAME=my_env
# if you need the environment directory to be named something other than the environment name, change this line
export ENVDIR=$ENVNAME

# these lines handle setting up the environment; you shouldn't have to modify them
export PATH
mkdir $ENVDIR
tar -xzf $ENVNAME.tar.gz -C $ENVDIR
. $ENVDIR/bin/activate

# modify this line to run your desired Python script and any other work you need to do
python3 classification.py

# Check if a new CSV file was created
new_csv_files=$(ls *.csv 2> /dev/null)
if [ -n "$new_csv_files" ]; then
    echo "New CSV files generated by classification.py:"
    echo "$new_csv_files"

else
    echo "No new csv file"
fi

# Clean up the environment files
rm -rf $ENVDIR
